### ISSUE TITLE
使用方法不懂

### ISSUE THREAD

**Issue by zytomorrow** [cdhigh/Forwarder#2]
按照教程弄好了转发器，那个使用方法中的验证码不用改吧，只需要将config.py中SHARE_FUCK_GFW_SRV的值前面的网址替换成自己的网址吗？其余需要转发服务器的book需要一个个改吗

**Comment by cdhigh** [comment]
是的，仅需要修改config.py中的地址即可，其他的书籍都会使用此变量的值。
如果你不修改转发器的验证码，验证码也不用改。

**Comment by zytomorrow** [comment]
嗯啦。。。谢谢

**Comment by jslilei** [comment]
根据教程搭好了，验证的时候提示Forwarder(1.2.2) : thisurl?k=AUTHKEY&t=timeout&u=url，这算成功了吗？  如果我想修改验证码，在哪里修改呀？

**Comment by cdhigh** [comment]
成功了，修改KindleEar的config.py文件中的参数即可，
如果要修改验证码，可以在forworder源文件的开头修改。

**Comment by jslilei** [comment]
非常感谢cdhigh，kindleear给我带来了很多。
