### ISSUE TITLE
根据方法一搭建不成功

### ISSUE THREAD

**Issue by suoba** [cdhigh/Forwarder#5]
-----> Python app detected
-----> Installing requirements with pip
       You must give at least one requirement to install (see "pip help install")
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 41.3M
-----> Launching...
       Released v5
       https://saveforcollectinfo.herokuapp.com/ deployed to Heroku

=========================================================

看说明好像是requirements 缺少东西。

**Comment by cdhigh** [comment]
我已经用方法一帮别人搭建了好几个了，都没有什么问题。
如果现在不行，估计heroku又修改了什么规则吧。
不过就几十行代码，用heroku的demo工程然后将这几十行代码拷贝粘贴过去就好。

**Comment by Steven630** [comment]
> 我也有同样的问题，下面是build log：
> -----> Python app detected
> -----> Installing python-3.6.3
> -----> Installing pip
> -----> Installing requirements with pip
>        You must give at least one requirement to install (see "pip help install")
> -----> Discovering process types
>        Procfile declares types -> web
> -----> Compressing...
>        Done: 41.4M
> -----> Launching...
>        Released v3
>        https://forwarder154912.herokuapp.com/ deployed to Heroku

点进去提示Application Error。
要复制的代码是wsgi.py里的代码吗？能否麻烦具体说一下，十分感谢。

**Comment by ZJJane** [comment]
我用的也是这个方法，但是跟他一样不行，能详细说说怎么做吗？

**Comment by Sciroccogti** [comment]
我也是一模一样的报错。。

用了方法二报错一致
提示：You must give at least one requirement to install (see "pip help install")
log：No module named 'urllib2'

**Comment by Sciroccogti** [comment]
问题已找到：
在[这一行](https://github.com/cdhigh/Forwarder/blob/master/wsgi.py#L17)中urllib2已被urllib包含，因此import失败。
